logging:
  level: INFO
  loggers:
    com.revolut: DEBUG

database:
  driverClass: org.h2.Driver
  user: sa
  #  password:
  url: jdbc:h2:./persondb
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: validate # validates schema when service is started

message: Hi %s!, now you will learn about %s from Stack Abuse!
firstParameter: Friend
secondParameter: Dropwizard